### ISSUE TITLE
Question - how to enter data

### ISSUE THREAD

**Issue by gjwo** [JackKelly/UK-DALE_metadata#2]
Hi @JackKelly 
I had assumed that data was entered as text into .yaml files, then I discovered https://github.com/JackKelly/UK-DALE_metadata/blob/master/convert_uk-dale_to_NILM_Metadata.py Does this mean you entered the data in python and then used this code to generate the yaml files? If so was this to save typing?

**Comment by JackKelly** [comment]
> I had assumed that data was entered as text into .yaml files

yes, that is almost certainly what you should do if starting from scratch.

`convert_uk-dale_to_NILM_Metadata.py` only exists because I wrote some metadata for UK-DALE a long time ago, before NILM Metadata existed, and I wanted a Python script to convert from the old metadata to NILM Metadata!

**Comment by gjwo** [comment]
Newbie yaml questions! 
looking at building1.yaml, I take it that "-" in the first column after the "appliances:" tag denotes the start of the definition of an individual appliance, the field order is random, which threw me.
-components is confusing, does this refer to any electric device, or to the base components described in https://github.com/nilmtk/nilm_metadata/blob/v0.2/central_metadata/appliance_types/components.yaml

In order to be consistent would this be an appropriate appliance template for me to use
appliances:
- original_name:
  description:
  manufacturer:
  type:
  subtype:
  room:  
  meters: [1]
  nominal_consumption:
  on_power_threshold: 
  instance: 1
  year_of_purchase:
  dates_active:

Questions
what is dominant_appliance: true for?
what about portable appliances?
what's the difference between nominal_consumption and on_power_threshold?
why no model or model number tag - could be significant as signatures become available
I would put the building related data first, then rooms, then meters then appliances i.e. least likely to change first, any reason not to do this?

**Comment by gjwo** [comment]
original layout mangled in previous comment

**Comment by JackKelly** [comment]
> looking at building1.yaml, I take it that "-" in the first column after the "appliances:" tag denotes the start of the definition of an individual appliance,

Yes.  Please see [WikiPedia's page on YAML](http://en.wikipedia.org/wiki/YAML) for a concise guide to YAML.

> the field order is random, which threw me.

It's random because, in this specific case, it's machine generated.

The rest of your questions are not specific to the UK-DALE metadata but are general to NILM Metadata so I have reposted them and will answer them here: https://github.com/nilmtk/nilm_metadata/issues/17
